
service: blog-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:GetItem
            - dynamodb:Scan
            - dynamodb:DeleteItem
          Resource:
            - arn:aws:dynamodb:us-east-1:361531004864:table/ItemTableNew
  

          
functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          path: /
          method: get
  createPostBlog:
    handler: src/createPostBlog.createPostBlog
    events:
      - http:
          path: /blog 
          method: post
          cors: true
          
  listPostsblog:
    handler: src/listPostsblog.listPostsblog
    events:
      - http:
          path: /blog
          method: get
          cors: true
  get:
    handler: src/get.get
    events:
      - http:
          path: blog/{id}
          method: get
          cors: true
  update:
    handler: src/update.upadate
    events:
      - http:
          path: blog/{id}
          method: put
          cors: true
  delete: 
    handler: src/delete.delete
    events:
      - http:
          path: blog/{id}
          method: delete
          cors: true

          
  
resources:
  Resources:
    BlogApiTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: BlogApiTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH